### ISSUE TITLE
container attributes are not getting logged "incomplete"

### ISSUE THREAD

**Issue by mutazalsallal** [sysflow-telemetry/sf-docs#27]
**Indicate project**
sf-collector

**Describe the bug**
the container attributes/properties are logged as incomplete

**To reproduce**
1. docker run -it --privileged ubuntu bash
2. apt-get update
3. apt-get install iputils-ping
4. ping 9.9.9.9

**Expected behavior**
to have the container details logged.

the logged event contains:
"container.id": "210861a2a4ea", "container.name": "incomplete", "container.imageid": "incomplete", "container.image": "incomplete/incomplete", "container.type": "CT_DOCKER", "container.privileged": false

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Kernel: Linux 5.3.0-26-generic
 - Architecture: x86-64
 - SysFlow version: sf-collector:edge
 - Container runtime (if applicable): Docker

**Comment by mutazalsallal** [comment]
I was thinking maybe sysflow cached the list of containers from docker apis
but Ive stopped the whole collector and started a new one
but that didnt solve it

**Comment by terylt** [comment]
Thanks Mutaz for the issue.  We've actually been working on this issue and recently fixed it for IKS.   The key point that we have noticed in this issue is 1.) what container runtime is being used, and 2.) how the sock file for that runtime is mounted into the container.   Can you provide a little detail about how you are starting up the collector?  Are you using the docker-compose from the deployments project?  And are you just using a local docker installation, with the docker container runtime?

**Comment by terylt** [comment]
The key point that we have found with mounting the sock files is to mount them inside the sf-collector with a prepended `/host` directory.  For example, if the runtime is docker:
`/host/var/run/docker.sock`  mount that file into the container.  The sysdig API automatically prepends `/host` to files its interested in.

**Comment by mutazalsallal** [comment]
Thanks Teryl
we dont have that issue anymore using the edge version.
will close this issue
