### ISSUE TITLE
helm chart deployment writing empty sysflow files in Kubernetes

### ISSUE THREAD

**Issue by terylt** [sysflow-telemetry/sf-docs#9]
**Indicate project**
collector, deployment

**Describe the bug**
Since moving the docker container from our internal registry to docker hub, our internal kubernetes deployment isn't properly collecting sysflow - it's printing empty sysflow files.  We anticipate this being a minor issue caused by moving all the images/containers outside our internal systems. We will fix over the next few days, but note this here in case their are any early adopters with the issue.

**To reproduce**
1. Deploy collector/exporter to cloud using helm charts
2. View file size as it gets dropped into S3.   It is empty. 

**Expected behavior**
File should collect sysflow.

**Environment (please complete the following information):**
 - OS: IBM Cloud cluster, kernel 4.4.0-148-generic
 - SysFlow version: 0.1rc1
 - Container orchestration framework and version (if applicable): kubernetes
 - Container runtime (if applicable): docker

**Comment by araujof** [comment]
Issue fixed by updating to the latest stable version (0.26.4) of sysdig. There was an issue with version 0.24.2 of the sysdig probe on this particular kernel (and also on newer/latest kernels, including 4.0.15-66 on Ubuntu 18.04 LTS), in which the host networking is brought down after the probe is loaded. 

[https://github.com/sysflow-telemetry/sf-collector/commits/0.1-rc2](https://github.com/sysflow-telemetry/sf-collector/commits/0.1-rc2)
